### ISSUE TITLE
No Audio when Airplaying to Eufy Genie (airplay 1) device

### ISSUE THREAD

**Issue by cdlenfert** [owntone/owntone-server#1977]
I noticed on the latest master branch that when OwnTone streams to my Eufy Genie speaker, no audio comes out of the speaker. Changing volume shows the changes in the round LED on top, so there is still communication, and OwnTone makes a successful connection. When I airplay directly from my iPhone, it plays from the Genie just fine. 

I tested a variety of previous commits, some of which failed to build for me, until I found one where streaming from OwnTone > Eufy Genie still worked. I'll share everything I know (and don't) below. Just let me know if I can provide more test results and/or logs.

Some AI assistance with troubleshooting and a tested fix that's working for me is below:

# AirPlay 1 streaming stops after PTP changes (Feb 20)

## What’s wrong

After a batch of AirPlay‑2/PTP work landed on Feb 20, OwnTone can no longer send audio to AirPlay 1/RAOP speakers. The connection still goes through — OPTIONS, SETUP, RECORD all succeed and the player shows “playing” — but the speaker never receives any RTP packets. iOS devices can still stream to the same speaker, so it isn’t broken on the device side.

This problem was reproduced on a RockPi with a eufy Genie‑1490.

## Good/bad commits

`git bisect` narrowed it down to the PTP commit:

* `14042406` (Feb 6) – last known good; audio works
* `8b8193fe` (pushed Feb 20) – first bad commit

All later commits inherit the issue.

## Build glitch

On this machine (libplist < 2.3) anything after the bad commit also fails to link with

```
outputs/airplay.c:2687: undefined reference to `plist_to_json'
```

That’s a side effect of the PTP changes and isn’t strictly required to reproduce the audio problem.

## What you hear/log

The server logs show the usual RAOP setup and then only progress SET_PARAMETER packets:

```
[player] device_start: Sending OPTIONS to 'eufy Genie-1490'
[player] Callback … status 1
[player] player: Player status: playing
[player] raop: send_progress: Sending SET_PARAMETER …
```

No RTP payload is ever sent. The speaker sits silent.

## Why it broke

The PTP additions include a new `sync_packet_ntp_make()` helper. That helper mistakenly adds
`+11025` to the RTP timestamp even though the latency byte (`0x07`) in the packet already tells
the speaker to delay 11025 samples. AirPlay 1 devices therefore think the stream started
11025 samples *ahead* of where it actually did, and simply drop all subsequent packets.

## Temporary fix

Revert the timestamp adjustment: use `pos` directly instead of `pos + 11025`. With that change
RTP audio is delivered correctly and playback resumes on the Genie. The PTP path (used by
AirPlay 2) is unaffected.

**Comment by ejurgensen** [comment]
Thanks for the report. Having OT working with all speakers is important, so really valuable with this quick testing.

I will try testing with some of my Airplay 1 speakers, and if I can't reproduce I might need some more info about the Genie.

**Comment by ejurgensen** [comment]
I can't reproduce this issue on my very old APEX nor on a newer device, both using Airplay 1. The timestamps OT is sending should match what Apple does, but maybe there is some special condition OT is not accounting for. Would it be possible for you to Wireshark playback start-up with an Apple sender (maybe Apple Music or iTunes would be easiest?) and your Eufy Genie?

**Comment by cdlenfert** [comment]
This is what I was able to get. I've never used wireguard and don't know how to interpret the files. If you need something else, please let me know.

[tcpdumps.zip](https://github.com/user-attachments/files/25916305/tcpdumps.zip)

**Comment by ejurgensen** [comment]
Thanks, very helpful. I could see what the problem was. I've made an attempted fix in the branch raop_timing1, as referenced above. Hope you can test.

Symptomatically, the AI was _almost_ right, at least if you ask me. While removing the latency altogether wouldn't be correct, moving it would be, so that's what I've done.

**Comment by cdlenfert** [comment]
Just tested the new branch and it's working for me. Thank you! Always
surprised with what the AI can do, but it certainly has its limitations.

**Comment by ejurgensen** [comment]
Unfortunately I found that moving (or removing) the latency breaks sync, so looks like a solution to this problem is going to be more complicated. I have to analyze some more.

**Comment by cdlenfert** [comment]
Ahh, yes I hadn't tested sync but it is broken for me as well.

**Comment by ejurgensen** [comment]
I think I have fixed it now without breaking sync, at least according to my tests. Let me know if you find otherwise.

**Comment by cdlenfert** [comment]
Thank you! Streaming to the Genie is working agian and it's playing in sync.
